### ISSUE TITLE
CC-0 License

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/mimerender-cookiecutter-ts#3]
We need to change the cookie cutters to CC-0.  @fm75 #2 @SylvainCorlay

**Comment by fm75** [comment]
I am not familiar with CC. Sounds like we need a different License verbiage.

**Comment by jasongrout** [comment]
First, I think making the cookie-cutters very permissive (e.g., CC-0) is a good idea.

However, if we want to make a policy of this, we should open an issue and/or PR to the governance repo, which is the official place for deciding and discussing project policy. 

Even after such a policy is put in place, license changes to an individual repo should never be merged until the contributors to the repo have explicitly approved it. For example, contributors to the repo commenting on the PR approving the change may be sufficient.

**Comment by ian-r-rose** [comment]
I agree with @jasongrout. The FSF also recommends CC0 for code snippets and examples: https://www.gnu.org/licenses/license-recommendations.html

**Comment by fm75** [comment]
Agree.

**Comment by blink1073** [comment]
I agree.
